baseURL = "https://mina.apache.org"
title = "Apache Mina"
languageCode = "en"

contentDir = "source"
publishDir = "target/content"

disablePathToLower = true
uglyURLs = true
enableRobotsTXT = true
disableBrowserError = true
timeout = 3000

disableKinds = ["taxonomy", "taxonomyTerm"]
ignoreFiles = [ ] # No files to ignore

# Highlighting config. See https://help.farbox.com/pygments.html
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "emacs"

# Enable Git variables like commit, lastmod
enableGitInfo = true

# If set to true, prevents Hugo from including the mermaid module if not needed (will reduce load times and traffic)
disableMermaid = false

# Specifies the remote location of the mermaid js
customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"

[markup.goldmark.renderer]
unsafe= true

[blackfriday]
# hrefTargetBlank = true # We don't want everything opened in a new window
fractions = false

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

[params]
version_asyncweb = "2.0.0-SNAPSHOT"
version_mina_2_0 = "2.0.25"
version_mina_2_1 = "2.1.8"
version_mina_2_2 = "2.2.3"
version_ftpserver_1_1 = "1.1.4"
version_ftpserver_1_2 = "1.2.0"
version_sshd = "2.13.2"
version_vysper = "0.7"
